### ISSUE TITLE
Assertion '__n < this->size()' failed

### ISSUE THREAD

**Issue by fervidnerd** [EmixamPP/linux-enable-ir-emitter#172]
**Ouput of `linux-enable-ir-emitter -v configure`**

```
DEBUG: Executing configure command.
INFO: Stand in front of and close to the camera and make sure the room is well lit.
INFO: Ensure to not use the camera during the execution.
DEBUG: Checking if /dev/video3 is a greyscale camera.
DEBUG: Checking if /dev/video2 is a greyscale camera.
/usr/include/c++/11/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::const_reference = const int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    112803 IOT instruction  sudo linux-enable-ir-emitter -v configure

```

**Output of `cat /etc/linux-enable-ir-emitter/*`**
```
- corrupted: false
  unit: 4
  selector: 6
  current:
    - 1
    - 3
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  maximum:
    - 1
    - 3
    - 3
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 9
  current:
    - 1
    - 0
    - 0
    - 0
  maximum:
    - 1
    - 0
    - 0
    - 0
  minimum:
    - 0
    - 0
    - 0
    - 0

```

**Output of `v4l2-ctl --list-devices`**
```
NexiGo HelloCam N930W Camera: N (usb-0000:0a:00.3-3.2.1):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
	/dev/media0
	/dev/media1
```

**Ouput of `for dev in /dev/video*; do echo $dev && v4l2-ctl -d $dev --list-formats-ext; done`**
```
/dev/video0
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.017s (60.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.017s (60.000 fps)
		Size: Discrete 854x480
			Interval: Discrete 0.017s (60.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 1920x1080
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.050s (20.000 fps)
		Size: Discrete 854x480
			Interval: Discrete 0.050s (20.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
/dev/video1
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

/dev/video2
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'GREY' (8-bit Greyscale)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
/dev/video3
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture


```

**Output of `ls -l /dev/v4l/by-path`**
```
lrwxrwxrwx 1 root root 12 Apr  2 20:13 pci-0000:0a:00.3-usb-0:3.2.1:1.0-video-index0 -> ../../video0
lrwxrwxrwx 1 root root 12 Apr  2 20:13 pci-0000:0a:00.3-usb-0:3.2.1:1.0-video-index1 -> ../../video1
lrwxrwxrwx 1 root root 12 Apr  2 20:13 pci-0000:0a:00.3-usb-0:3.2.1:1.2-video-index0 -> ../../video2
lrwxrwxrwx 1 root root 12 Apr  2 20:13 pci-0000:0a:00.3-usb-0:3.2.1:1.2-video-index1 -> ../../video3

```

**Give more information if you have**

**Additional info**
 - Computer (or camera) model: https://www.nexigo.com/collections/all/products/hellocam
 - Linux distribution: Ubuntu 22.04.4
 - Version of linux-enable-ir-emitter: 6.0.0-pre
