### ISSUE TITLE
(ThinkPad X280) Webcam unrecognized after ctrl-c

### ISSUE THREAD

**Issue by th1nhhdk** [EmixamPP/linux-enable-ir-emitter#177]
**Ouput of `linux-enable-ir-emitter -v configure`**

```
DEBUG: Executing configure command.
INFO: Stand in front of and close to the camera and make sure the room is well lit.
INFO: Ensure to not use the camera during the execution.
DEBUG: Checking if /dev/video0 is a greyscale camera.
^C Ctrl-c again if you really want to, be careful this could break the camera.
```

**Output of `cat /etc/linux-enable-ir-emitter/*`**
<details open>
<summary>output</summary>
<br>

```
- corrupted: false
  unit: 3
  selector: 2
  current:
    - 2
  maximum:
    - 3
  minimum:
    - 3
- corrupted: false
  unit: 4
  selector: 2
  current:
    - 0
    - 32
  maximum:
    - 255
    - 255
  minimum:
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 3
  current:
    - 0
  maximum:
    - 255
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 4
  current:
    - 0
    - 0
  maximum:
    - 255
    - 255
  minimum:
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 5
  current:
    - 255
    - 0
  maximum:
    - 255
    - 255
  minimum:
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 6
  current:
    - 1
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 7
  current:
    - 1
  maximum:
    - 13
  minimum:
    - 1
- corrupted: false
  unit: 4
  selector: 8
  current:
    - 3
  maximum:
    - 255
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 9
  current:
    - 0
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 12
  current:
    - 0
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 13
  current:
    - 0
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
    - 0
  minimum:
    - 0
    - 0
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 14
  current:
    - 0
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
    - 0
  minimum:
    - 0
    - 0
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 15
  current:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
- corrupted: false
  unit: 4
  selector: 16
  current:
    - 2
  maximum:
    - 3
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 21
  current:
    - 0
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 22
  current:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
- corrupted: false
  unit: 4
  selector: 23
  current:
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
  minimum:
    - 0
    - 0
    - 0
- corrupted: false
  unit: 3
  selector: 3
  current:
    - 23
    - 17
  maximum:
    - 100
    - 25
  minimum:
    - 240
    - 10
- corrupted: false
  unit: 4
  selector: 2
  current:
    - 0
    - 32
  maximum:
    - 255
    - 255
  minimum:
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 3
  current:
    - 0
  maximum:
    - 255
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 4
  current:
    - 0
    - 0
  maximum:
    - 255
    - 255
  minimum:
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 5
  current:
    - 255
    - 0
  maximum:
    - 255
    - 255
  minimum:
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 6
  current:
    - 1
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 7
  current:
    - 1
  maximum:
    - 13
  minimum:
    - 1
- corrupted: false
  unit: 4
  selector: 8
  current:
    - 3
  maximum:
    - 255
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 9
  current:
    - 0
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 12
  current:
    - 0
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 13
  current:
    - 0
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
    - 0
  minimum:
    - 0
    - 0
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 14
  current:
    - 0
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
    - 0
  minimum:
    - 0
    - 0
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 15
  current:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
- corrupted: false
  unit: 4
  selector: 16
  current:
    - 2
  maximum:
    - 3
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 21
  current:
    - 0
  maximum:
    - 1
  minimum:
    - 0
- corrupted: false
  unit: 4
  selector: 22
  current:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
- corrupted: false
  unit: 4
  selector: 23
  current:
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
  minimum:
    - 0
    - 0
    - 0
- corrupted: false
  unit: 4
  selector: 27
  current:
    - 0
    - 0
    - 0
    - 255
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  maximum:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
  minimum:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
[]
```

</details>

**Output of `v4l2-ctl --list-devices`**
```
SPCA2085 PC Camera: PC Camera (usb-0000:00:14.0-5):
        /dev/video0
        /dev/video1
        /dev/media0

SPCA2087 PC Camera: PC Camera (usb-0000:00:14.0-8):
        /dev/video2
        /dev/video3
        /dev/media1
```
- It used to be like #148 before running this program

**Ouput of `for dev in /dev/video*; do echo $dev && v4l2-ctl -d $dev --list-formats-ext; done`**
```
/dev/video0
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'YUYV' (YUYV 4:2:2)
                Size: Discrete 160x120
                        Interval: Discrete 0.033s (30.000 fps)
/dev/video1
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

/dev/video2
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'YUYV' (YUYV 4:2:2)
                Size: Discrete 160x120
                        Interval: Discrete 0.033s (30.000 fps)
/dev/video3
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture
```

**Output of `ls -l /dev/v4l/by-path`**
```
total 0
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usb-0:5:1.0-video-index0 -> ../../video0
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usb-0:5:1.0-video-index1 -> ../../video1
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usb-0:8:1.0-video-index0 -> ../../video2
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usb-0:8:1.0-video-index1 -> ../../video3
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usbv2-0:5:1.0-video-index0 -> ../../video0
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usbv2-0:5:1.0-video-index1 -> ../../video1
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usbv2-0:8:1.0-video-index0 -> ../../video2
lrwxrwxrwx. 1 root root 12 May 21 13:37 pci-0000:00:14.0-usbv2-0:8:1.0-video-index1 -> ../../video3
```

**Give more information if you have**

- I Ctrl + C'ed because at the press Y or N no window appeared for a long time
- After that the device names are messed up, both the webcam and IR camera in both Windows and Linux stopped working
- In device manager the device show up as "Unknown USB Device (Device Descriptor Request Failed)"

**Additional info**
 - Computer (or camera) model:  ThinkPad X280
 - Linux distribution: Fedora Linux 40 (KDE Plasma)
 - Version of linux-enable-ir-emitter: linux-enable-ir-emitter 6.0.0-beta
